apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hmis-mf-ingress
spec:
  ingressClassName: traefik
  rules:
  - host: test-dev.justtrytech.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hmis-mf-service
            port:
              number: 80
